In [3]:
import numpy as np

python_list = [1,2,3,4,5]
numpy_array = np.array(python_list)
print(numpy_array)

[1 2 3 4 5]


In [5]:
print(type(python_list),type(numpy_array))
print(numpy_array.dtype)

<class 'list'> <class 'numpy.ndarray'>
int64


In [9]:
print(np.zeros(5))
print(np.ones(3))
print(np.arange(0,10,2))
print(np.linspace(0,1,6))
print(np.random.randint(1,100, size=5))


[0. 0. 0. 0. 0.]
[1. 1. 1.]
[0 2 4 6 8]
[0.  0.2 0.4 0.6 0.8 1. ]
[ 1 60 71 89 82]


In [15]:
import csv
import numpy as np

quantities, prices = [], []
with open(r"C:\Users\Aun Zaidi\Downloads\brewbuzz_raw_orders.csv", newline="", encoding="utf-8") as f:
    reader = csv.DictReader(f)
    for row in reader:
        try:
            q = int(row["quantity"])
            p = float(row["price"])
            if q > 0 and p > 0:
                quantities.append(q)
                prices.append(p)
        except ValueError:
            continue
qty_arr = np.array(quantities)
price_arr = np.array(prices)

KeyError: 'price'